# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 5
  # docs: https://docs.sqlalchemy.org/en/14/core/engines.html
  # TODO: import password from env var
  db_url: !env_var HASS_DB_URL

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: !env_var MQTT_BROKER
  protocol: 3.1
  keepalive: 60
  client_id: hassio-1
  username: !env_var MQTT_USER
  password: !env_var MQTT_PASSWORD
