# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 5
  # docs: https://docs.sqlalchemy.org/en/14/core/engines.html
  db_url: !env_var HA_DB_URL mysql://homeassistant:password@mariadb:3306/ha_db

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  advertise_ip: !env_var HOST_IP 10.0.0.43

mqtt:
  broker: !env_var MQTT_BROKER mosquitto
  protocol: 3.1
  keepalive: 60
  client_id: hassio-1
  username: !env_var MQTT_USER mosquitto
  password: !env_var MQTT_PASSWORD
