version: '3.7'

services:
  homeassistant:
    depends_on:
      - deconz

  # Zigbee stick software, ZHA is a better option if you use multiple vendors IMO
  deconz:
    image: marthoc/deconz
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      # look for your conbee using: `lsusb`
      # and `udevadm info --name=/dev/tty<device>`
      - /dev/ttyACM0:/dev/ttyACM0:rwm
    ports:
      - 8089:8089
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=8089
      - DECONZ_WS_PORT=8089
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
