version: '3.7'

services:
  # Home assistant core
  homeassistant:
    build:
      context: .
    # image: homeassistant/home-assistant:latest
    ## Security Warning: Only enable host network mode to find integrations
    # network_mode: host
    # user: "${LOCAL_USER}:${LOCAL_USER}"
    expose:
      - 8123
    ports:
      - "8123:8123"
      - "21063:21063" # Homekit integration default port
    environment:
      HA_DB_URL: "${HA_DB_URL}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
    volumes:
      - ./data/homeassistant:/config
      - ./overrides/homeassistant/config/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Dangerous: Sharing dbus in order for mDNS to work
      # TODO: Remove this as soon a working alternative is found
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
    devices: # Bluetooth, zigbee, z-wave
      - /dev/ttyACM0:/dev/ttyACM0:rwm # Conbee II
    restart: unless-stopped
    depends_on:
      - mosquitto
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8123" ]
      interval: 30s
      timeout: 10s
      retries: 6
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`ha.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.homeassistant.service=homeassistant"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  # mqtt server
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - "./data/mosquitto/config:/mosquitto/config"
      - "./data/mosquitto/data:/mosquitto/data"
      - "./data/mosquitto/log:/mosquitto/log"
    environment:
      TZ: "${TIMEZONE}"
    user: "${LOCAL_USER}:${LOCAL_USER}"

  # Node-RED, automate with blocks
  nodered:
    image: nodered/node-red:latest
    expose:
      - 1880
    ports:
      - "1880:1880"
    volumes:
      # Local path where all Node-RED config will be stored.
      - ./data/nodered:/data
    depends_on:
      - homeassistant
    environment:
      TZ: "${TIMEZONE}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    restart: unless-stopped
    labels:
      - "traefik.http.routers.nodered.rule=Host(`nodered.${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.nodered.service=nodered"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"



  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8181:8080"
      # HTTPS
      - "443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
