version: '3.7'

services:
  # Manage the database
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "mariadb"
      ADMINER_PLUGINS: "tables-filter tinymce"
    ports:
      - 8088:8080
    depends_on:
      - mariadb
