version: '3.7'

services:

  homeassistant:
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`ha.${NETWORK_DOMAIN}`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"


  nodered:
    labels:
      - "traefik.http.routers.nodered.rule=Host(`nodered.${NETWORK_DOMAIN}`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.5.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8181:8080"
      # HTTPS
      - "443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
