services:
  # MariaDb
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: ha_db
      MARIADB_USER: homeassistant
      MARIADB_PASSWORD: "${HA_DB_PASSWORD}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    volumes:
      # Local path where the database will be stored.
      - ./data/mariadb:/var/lib/mysql:rw
    # Expose in the internal docker network
    expose:
      - 3306
    # Don't expose ports to the outside
    # ports:
    #   - "3306:3306"

